# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_auto_20161026_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(upload_to=''),
        ),
    ]
