# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-29 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0003_auto_20161026_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper',
            new_name='document',
        ),
    ]
