# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_auto_20161204_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadlineType',
            field=models.CharField(choices=[('paperSubmission', 'Paper Submission'), ('paperSelection', 'paperSelection'), ('paperAssign', 'paperAssign'), ('paperReview', 'paperReview'), ('paperRate', 'paperRate')], max_length=500),
        ),
    ]
