# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0003_auto_20161205_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadlineType',
            field=models.CharField(choices=[('paperSubmission', 'Paper Submission'), ('paperSelection', 'Paper Selection'), ('paperAssign', 'Paper Assign'), ('paperReview', 'Paper Review'), ('paperRate', 'Paper Rate')], max_length=500),
        ),
    ]
