# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='document',
        ),
        migrations.AddField(
            model_name='paper',
            name='paper',
            field=models.FileField(default=123, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='formats',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Word', 'Word')], max_length=5),
        ),
    ]
